language: scala
scala:
- 2.10.5
script:
- sbt ++$TRAVIS_SCALA_VERSION clean assembly
env:
  global:
    secure: vdLt9Xx1o4NS60n8zfcMmyp8BbtR5OIwfpOYipFSdIVdjEiCTkoo8IJOCi16tZsUN7PpAvhmxrjBsyKtJrw0SCCtAqZiEfYbSs+fVUTOno3Ut571xlmu8tHP4LzWAjCsc+7QsTpQi7TxqlI8LXmCmij2B2OAnFotBjddAQBc9zYHEAHVg9U+9Ing7ZRbuDVZmeYlft3aVKtDQiE6+QUUQ3BR6eAteEl/xj1LkT7YmylkKZktZS659YWUUDyqsUskeB7S3HDFKbR/ozrLEfyPoqoQgv8K/Fzok4AQqVpAy+3MyhJNk9ZQ+jvbCNPNBH7Bj+VTtlONG3iDhCaDLyRc49Q6HJxSgBIzUFehgg6132vqStSpUv7Sa8sCVkzrGUHZf5yu1iEer02TWp0HpLR/PxCJqreuZ+e96oi91UukVR17Sn5pzcNp3bDELx1wNM/j+DxYrykMsJnlxYlGpVfMp0Z5Ol7HCKLomvWNCFHsnuEN5Z7XzebX8vzH+8G6VAfc/C4flgxWw5vfxb3o7eYXRwwS+2jAiTzi4zHvOJHOFOzhnWxSSNvjXC92MUqA2eJNiEqzmTDvWk6pe33YTcgD+j6CLoeodjf+dgnnGAm1oszN1JlFX3Hg8fymZOxDSDTfkABLhAf9M9tv+uknCGzsiMRAe2AnGqeU4A9P3hAO74U=
before_deploy:
- git config --local user.name "witlox"
- git config --local user.email "pim@witlox.io"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: hXdIoL7MCioWHicvTV1sS3Mm1BOzotp0hSv4mIu1OQdcp5gIwhGjuBmxUqRoQtvAZqdsGRvNxwsI0oALVnlU9R6oLGPsDwLvLqqPWjCttNwlYSLMhaXVKNKyZzOHT1o7ICVkEvp7gJfQIYviohhAReFXCSTSm+HBb0L+4blKnqEqMoa6GN6jKm948AM5FRi8KvNSdANwLixC6WbM5l8nNDIj1z/GcB+hRGsoCSbeEPCxDS7xBY0z/FzPfWxORbbpMmOvT9iMxz2SuaabM1g/UtHNcIIwV+dgSEC0JGBxVncBW0z61rkYnrWTBn/STWsSwkHhvDsFW1E2Ou9neOQDv7Dw1wollnEhoNtBkody7wyPhGU0uvz2k4SOhddHL3q5HNJ/1Dn9jyzKzxsXdh8H+jlaxiC8Ep4ScmxXLYawUlZq7rS5FnpOMw2aD95/wupbcGIKK+2PF16X+nJZs9aVdP804QngE/xmWUFWrTst/1sTdxvvuilBcka8DCAe/CyGnyBEaQxkbx/6oIyFxupQV/ugA6GDd3HO6+uxJEPbNfjW+aEeNwpC26oyXMBaG65w/LOkpenzcd4LqYIleW7lWCGoerWUKKLTmw2GFdCVPhdR4i0Ej/Y4vhrDXgO6eOVOIGkgkiIHxPkA8IAhzExXAlEIQly4yEl0VQSwK7cBhGY=
  file_glob: true
  file: "target/**/*.jar"
  on:
    tags: true
  skip_cleanup: true
