language: scala
scala:
- 2.10.5
script:
- sbt ++$TRAVIS_SCALA_VERSION clean assembly
before_deploy:
- git config --local user.name "witlox"
- git config --local user.email "pim@witlox.io"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: r/WoDvWetUBVdoJk9VX3/twaPC8n8wdbY9mDf0po0pDPnQjKgw9mMyaNeRv0QV090uX0ISn77+lgz8FzYIVy7ktL+JmmIW+yTxyV54Ax0ydA7cs0FtvmJRfysvP6CbGtBCXop5VKXbHEC7XugCfAJKFtcD4NU+bVBkjGfEO3XCIBCT5fi0rvXBxz4Z0+JBMRXakNp0AZEREorbvHsP61UQSkGqQzzQB6uefx/I9+RzWg0kcAkzpB0PLfAjUFXmi5Q2W9m39TYj0gI11tkl3EH50Xt/ArxZdkGnxhm7tMoTUfzORAF3wQsdvE2Rc8nFtIvnR2TzFzq03q/EwLMLscB0V7Z45jf2T1hHUR4Ed5wVqE9YQA5+zO1GT5xmNmB93qCkzVIB1oIV8Yi/H0aSQZF2Vi532+jShEyEA97Dw8Up/jooDdDV79W1CargC3ykf05yg03kEJUUlQgQYlKDGLJO8pWTjs/CH46KzrkvKG6gndLcNYzfhbWk0y6y4Z8XBIBlZwoxmMWlfTs0n4oXiD0RaGzhojsA7C0srMi7RCUgyoBvowWAfS4NvMk1XGdL7tdBpkeNqivqChDgcU2Pv62zpX1dQqlpilhINR5IedxYBK2Zyg6sjU+qUU0K9gaiZorAEZTXqdwnHOeyKkmkU5pTLFnt/DVXpqzRVfNtEMUPc=
  file_glob: true
  file: "target/**/*.jar"
  on:
    tags: true
  skip_cleanup: true
